platform :ios, '8.0'
use_frameworks!
target ‘XiAnJMApp’ do  
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'Masonry', '~> 1.0.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'SSZipArchive', '~> 1.8.1'
end
